name: "Build and upload apk prod"

on:
    push:
        branches:
            - "main"
        tags:
            - "v*"

jobs:
    build-and-upload-apk:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set Up JDK
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: 'gradle'
        
            - name: Run gradle tests
              run: ./gradlew test
        
            - name: Build gradle project
              run: ./gradlew build
        
            - name: Build apk release project
              run: |
                ./gradlew assembleRelease

            - name: Upload apk release
              uses: actions/upload-artifact@v4
              with:
                name: eventhub-release-apk
                path: app/build/outputs/apk/release/
              