name: "Build and upload apk dev"

on: push

jobs:
    build-and-upload-apk:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set Up JDK
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
                cache: 'gradle'
        
            - name: Run gradle tests
              run: ./gradlew test
        
            - name: Build gradle project
              run: ./gradlew build
        
            - name: Build apk debug project
              run: |
                ./gradlew assembleDebug

            - name: Upload apk debug
              uses: actions/upload-artifact@v4
              with:
                name: eventhub-debug-apk
                path: app/build/outputs/apk/debug/

              